#pipeline

name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: aleksandrobg/calc:${{ github.sha }}

      - name: Test with Docker
        run: |
          docker run -v $(pwd):/app -w /app aleksandrobg/calc:${{ github.sha }} /bin/bash -c "pip install -r requirements.txt && python -m unittest test_calculadora.py"

      - uses: AppThreat/sast-scan-action@master
        with:
          type: "python"

      - name: Send report to Telegram bot
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "Relatorio de teste disponivel em https://github.com/aleksandrobg/devops-pipeline/actions/runs/${{ github.run_id }}"

  deploy-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: echo "Testado e finalizado!"

